version: "3.9"

services:

  docker_tradeforce:
    container_name: tradeforce_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - docker_postgres
    volumes:
      - ./:/opt/tradeforce
      - ./examples/:/user_code
    entrypoint: [ "/bin/bash" ]

  docker_postgres:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5433
    command: -p 5433

  # docker_mongodb:
  #   container_name: mongodb
  #   image: mongo:6.0.4-jammy
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: tradeforce
  #     MONGO_INITDB_ROOT_PASSWORD: tradeforce
  #   ports:
  #     - 27017:27017
    # volumes:
    #   - /data/tradeforce_db:/data/db

