[tool.poetry]
name = "tradeforce"
version = "0.1.0"
description = "Framework for Backtesting and Live-Trading. Hyperparameter-Optimization of Trading-Strategies through performant simulations."
authors = ["cyclux <nevermind@cyclux.de>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.10,<3.12"
numpy = "<1.24"
numba = "^0.56.4"
bitfinex-api-py = "^2.0.6"
pandas = "^1.5.3"
pyarrow = "^11.0.0"
optuna = "^3.1.0"
tqdm = "^4.65.0"
pymongo = "^4.3.3"
psycopg2 = "^2.9.5"
tensorflow-probability = "^0.19.0"
numexpr = { version = "^2.8.4", optional = true }
bottleneck = { version = "^1.3.7", optional = true }
pyyaml = { version = "^6.0", optional = true }
asyncio = "^3.4.3"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.260"
mypy = "^1.1.1"
types-psycopg2 = "^2.9.21.9"
types-pytz = "^2023.2.0.1"
types-pyyaml = "^6.0.12.9"
types-tqdm = "^4.65.0.1"
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
pandas-stubs = "^1.5.3.230321"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120


[tool.mypy]
exclude = ['archive', 'analysis']
