version: "3.9"

services:

  tradeforce:
    container_name: tradeforce_dev
    image: tradeforce_dev:latest
    depends_on:
      - postgresql
    volumes:
      - ../:/opt/tradeforce
    entrypoint: [ "poetry", "run", "python", "examples/live_trader.py" ]
    # entrypoint: [ "/bin/bash" ]
    # docker run -it --rm --name tradeforce_dev_env -v ${PWD}:/opt/tradeforce tradeforce_dev /bin/bash

  mongo:
    container_name: mongodb
    image: mongo:6.0.4-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tradeforce
      MONGO_INITDB_ROOT_PASSWORD: tradeforce
    ports:
      - 27017:27017
    volumes:
      - /data/tradeforce_db:/data/db
    # volumes:
    #   - /mnt/xfs_mongodb:/data/db

  postgresql:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    # volumes:
    #   - db:/var/lib/postgresql/data

    # volumes:
    #   postgresql:
    #     driver: local
    #   mongo:
    #     driver: local
