%YAML 1.2
---
trader:
  id: 1
  creds_path: "exchange_creds.cfg"
  dry_run: False
  maker_fee: 0.10
  taker_fee: 0.20
  budget: 1100
  strategy:
    amount_invest_fiat: 100
    investment_cap: 0
    buy_opportunity_factor: 0.10
    buy_opportunity_boundary: 0.05
    prefer_performance: "positive"
    hold_time_limit: 1000
    profit_factor: 1.70
    profit_ratio_limit: 1.01
    window: 180

market_history:
  candle_interval: "5min"
  history_timeframe: "60days"
  base_currency: "USD"
  exchange: "bitfinex"
  load_history_via: "feather"
  check_db_consistency: True
  dump_to_feather: True
  backend: "mongodb"
  backend_host: "localhost:1234"
  mongo_collection: "bfx_history_2y"
  update_history: False
  run_exchange_api: True
  keep_updated: True

simulation:
  sim_start:
  sim_timeframe:
  snapshot_size: -1
  snapshot_amount: 1
