%YAML 1.2
---
trader:
  id: 1
  run_live: True
  creds_path: "exchange_creds.cfg"
  dry_run: False
  maker_fee: 0.10
  taker_fee: 0.20
  budget: 1100
  strategy:
    amount_invest_fiat: 100
    investment_cap: 0
    buy_opportunity_factor: 0.10
    buy_opportunity_boundary: 0.05
    prefer_performance: 1
    hold_time_limit: 1000
    profit_factor: 1.70
    profit_ratio_limit: 1.01
    moving_window_hours: 180

backend:
  backend: "mongodb"
  backend_host: "localhost:1234"
  local_cache: True

market_history:
  name: "bfx_history_2y"
  exchange: "bitfinex"
  base_currency: "USD"
  candle_interval: "5min"
  history_timeframe: "60days"
  update_mode: "live"

simulation:
  sim_start:
  sim_timeframe:
  snapshot_size: -1
  snapshot_amount: 1
