%YAML 1.2
---

market_history:
  name: bitfinex_history
  base_currency: USD
  candle_interval: 5min
  exchange: bitfinex
  fetch_init_timeframe_days: 100
  update_mode: none
  force_source: local_cache

backend:
  dbms: postgresql
  dbms_connect_db: postgres
  dbms_host: docker_db
  dbms_port: 5433
  dbms_pw: postgres
  dbms_user: postgres
  local_cache: True
  check_db_sync: False

trader:
  id: 1
  budget: 1000
  maker_fee: 0.1
  taker_fee: 0.2
  run_live: False

  strategy:
    amount_invest_per_asset: 100
    moving_window_hours: 160
    buy_signal_boundary: 0.05
    buy_signal_score: 0.1
    buy_signal_preference: 1
    profit_factor_target: 1.1
    hold_time_days: 4
    profit_factor_target_min: 1.01

simulation:
  subset_size_days: 30
  subset_amount: 10
  train_val_split_ratio: 0.8
