version: "3.9"

services:

  docker_tradeforce:
    container_name: tradeforce
    image: tradeforce:latest
    depends_on:
      - docker_postgres
    volumes:
      - ./tradeforce_entrypoint.sh:/home/tf_docker/tradeforce_entrypoint.sh
      - ./:/home/tf_docker/user_code/
    environment:
      - RUN_JUPYTERLAB=${RUN_JUPYTERLAB}
      - RUN_MARKET_SERVER=${RUN_MARKET_SERVER}
    entrypoint: ["/bin/bash", "tradeforce_entrypoint.sh" ]
    ports:
      - 8889:8889
      #- 5000:5000

  docker_postgres:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432


# $env:RUN_MARKET_SERVER=True; docker-compose up; Remove-Item Env:\RUN_MARKET_SERVER


  # docker_mongodb:
  #   container_name: mongodb
  #   image: mongo:6.0.4-jammy
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: tradeforce
  #     MONGO_INITDB_ROOT_PASSWORD: tradeforce
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /data/tradeforce_db:/data/db
