version: "3.9"

services:

  docker_tradeforce:
    container_name: tradeforce
    image: cyclux/tradeforce:latest
    depends_on:
      - docker_postgres
    volumes:
      - ./tradeforce_entrypoint.sh:/home/tf_docker/tradeforce_entrypoint.sh
      - ./:/home/tf_docker/user_code/
    environment:
      - RUN_JUPYTERLAB=${RUN_JUPYTERLAB}
      - RUN_MARKET_SERVER=${RUN_MARKET_SERVER}
    entrypoint: ["/bin/bash", "tradeforce_entrypoint.sh" ]
    ports:
      - 8889:8889 # jupyterlab

  docker_postgres:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5433
    command: -p 5433

# Alternative: Use MongoDB instead of Postgres
# The Tradeforce configuration needs to be adapted accordingly.

  # docker_mongodb:
  #   container_name: mongodb
  #   image: mongo:6.0.4-jammy
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: tradeforce
  #     MONGO_INITDB_ROOT_PASSWORD: tradeforce
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /data/tradeforce_db:/data/db

# ------------------
# Window Powershell
# ------------------

# Run dedicated market server
# $env:RUN_MARKET_SERVER="True"; docker-compose up; Remove-Item Env:\RUN_MARKET_SERVER

# Run JupyterLab
# $env:RUN_JUPYTERLAB="True"; docker-compose up; Remove-Item Env:\RUN_JUPYTERLAB

# -----------
# Linux Bash
# -----------

# Run dedicated market server
# RUN_MARKET_SERVER="True" docker-compose up

# Run JupyterLab
# RUN_JUPYTERLAB="True" docker-compose up


